drop table if exists compilations_of_events, compilations, requests, events, users, categories;

create table if not exists users (
  id bigint primary key generated by default as identity,
  name varchar(255),
  email varchar(255) unique
);

create table if not exists categories (
  id bigint primary key generated by default as identity,
  name varchar(255) unique
);

create table if not exists events (
  id bigint primary key generated by default as identity,
  annotation varchar(2000),
  category bigint references categories(id),
  created_on timestamp without time zone,
  description varchar(7000),
  eventDate timestamp without time zone,
  initiator bigint references users(id) on delete cascade,
  lat real,
  lon real,
  paid bool,
  participantLimit int,
  published_on timestamp without time zone,
  requestModeration bool,
  title varchar(120),
  state varchar(50)
);

create table if not exists requests (
  id bigint primary key generated by default as identity,
  created timestamp without time zone,
  id_user bigint references users(id) on delete cascade,
  id_event bigint references events(id) on delete cascade,
  status varchar(50)
);

create table if not exists compilations (
  id bigint primary key generated by default as identity,
  pinned bool,
  title varchar(50)
);

create table if not exists compilations_of_events (
  id bigint primary key generated by default as identity,
  id_compilation bigint references compilations(id) on delete cascade,
  id_event bigint references events(id) on delete cascade
);