create table if not exists view_stats (
  id bigint primary key generated by default as identity not null,
  app varchar(255),
  uri varchar(255),
  hits bigint
);

create table if not exists endpoint_hit (
  id bigint primary key generated by default as identity not null,
  app varchar(255),
  uri varchar(255),
  ip varchar(255),
  timestamp timestamp without time zone
);